version: '3.9'
services:
  backend:
    build: ./acc_backend
    container_name: account-backend
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      OAUTH_ISSUER: ${OAUTH_ISSUER}
      OAUTH_ID: ${OAUTH_ID}
      OAUTH_SECRET: ${OAUTH_SECRET}
      GOOGLE_AUTH: ${GOOGLE_AUTH}

  frontend:
    build: ./shop-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
